"""
Deep comparison: extracts every paragraph from the generated Word document
and prints it alongside what the UI preview would render for the same form data.
Highlights all discrepancies.

Run: python tests/compare_ui_vs_doc.py
"""

import os
import sys
import re
import html

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from docx import Document
from lxml import etree

from services.document_generator import DocumentGenerator
from services.loi_form_data import (
    LoiFormData,
    DepositStructure,
    DueDiligenceType,
    CommissionType,
    SignatureBlockType,
    SignatureEntity,
)
from services.number_to_words import to_legal_dollar_string, convert_to_words

W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
TEMPLATE_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "Templates", "LOI_Template.docx")


def _qn(tag: str) -> str:
    prefix, local = tag.split(":")
    ns = {"w": W_NS}
    return f"{{{ns[prefix]}}}{local}"


def get_visible_paragraphs(body) -> list:
    """Extract visible text per paragraph (excluding deleted runs)."""
    result = []
    for para in body.iter(_qn("w:p")):
        texts = []
        for t in para.iter(_qn("w:t")):
            # Skip if inside a w:del element
            parent = t.getparent()
            in_del = False
            while parent is not None:
                if parent.tag == _qn("w:del"):
                    in_del = True
                    break
                parent = parent.getparent()
            if not in_del:
                texts.append(t.text or "")
        text = "".join(texts).strip()
        if text:
            result.append(text)
    return result


def get_header_visible_text(doc) -> list:
    """Extract visible header paragraphs."""
    result = []
    for section in doc.sections:
        h = section.header
        if not h:
            continue
        for para in h._element.iter(_qn("w:p")):
            texts = []
            for t in para.iter(_qn("w:t")):
                parent = t.getparent()
                in_del = False
                while parent is not None:
                    if parent.tag == _qn("w:del"):
                        in_del = True
                        break
                    parent = parent.getparent()
                if not in_del:
                    texts.append(t.text or "")
            text = "".join(texts).strip()
            if text:
                result.append(text)
    return result


def strip_html(s: str) -> str:
    """Strip HTML tags and decode entities for comparison."""
    s = re.sub(r'<[^>]+>', '', s)
    s = html.unescape(s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s


def fmt_period(value: int, unit: str = "days") -> str:
    return f"{convert_to_words(value).lower()} ({value}) {unit}"


def fmt_period_val(value: int) -> str:
    """Format period value WITHOUT unit (matching document_generator._format_period)."""
    return f"{convert_to_words(value).lower()} ({value})"


def fmt_dollar(amount: float) -> str:
    return to_legal_dollar_string(amount)


def normalize(s: str) -> str:
    """Normalize text for comparison: collapse whitespace, strip."""
    return re.sub(r'\s+', ' ', s).strip()


def strip_letter_prefix(s: str) -> str:
    """Strip auto-numbered letter prefixes like 'A. ', 'B. ' etc.
    These are auto-generated by Word's StandardL1 style numbering
    and don't appear in w:t text."""
    return re.sub(r'^[A-L]\.\s+', '', s)


# =========================================================================
# Build the UI preview text for a given form configuration
# =========================================================================
def build_ui_preview_text(form: LoiFormData) -> list:
    """Reconstructs what app.py's preview would render, returns list of text blocks."""
    lines = []

    # Page 1 header is in the document's header section, not the body.
    # Skipping it for body-text comparison.

    # Date
    lines.append(form.date)

    # Address block
    if form.seller_address_line1:
        lines.append(form.seller_address_line1)
    if form.seller_address_line2:
        lines.append(form.seller_address_line2)
    if form.seller_address_line3:
        lines.append(form.seller_address_line3)
    lines.append(f"Attn: {form.attention_name}" if form.attention_name else "Attn: [_______________]")

    # Re: line
    prop = form.property_address or "[Address, City, State]"
    lines.append(f'Re:  Proposal for the acquisition of {prop} (\u201cProperty\u201d)')

    # Salutation
    sal = form.salutation or "[Mr./Mrs./Ms._________]"
    lines.append(f"{sal}:")

    # Opening paragraph
    seller = form.seller_name or "[______________]"
    lines.append(
        f'On behalf of Subtext Acquisitions, LLC, a Missouri limited liability company, or its assignee '
        f'(\u201cPurchaser\u201d), we are pleased to submit this non-binding proposal to purchase the above-referenced '
        f'Property from {seller} (\u201cSeller\u201d) on the terms and conditions set forth herein.'
    )
    lines.append("The terms of the proposed sale are as follows:")

    # A. Property
    lines.append(
        'A. Property. The proposal is for the Property described herein together with all improvements, rights of way, '
        'easements, hereditaments and appurtenances in any way related to or benefiting the Property. '
        'The Property is legally described and generally depicted on Exhibit A attached hereto.'
    )

    # B. Purchase Price
    if form.purchase_price and form.purchase_price > 0:
        pp_words = convert_to_words(int(form.purchase_price))
        pp_num = f"{int(form.purchase_price):,}"
    else:
        pp_words = "[_________________]"
        pp_num = "[_________]"
    lines.append(
        f'B. Purchase Price. {pp_words} and 00/100 Dollars (${pp_num}.00) '
        f'(the \u201cPurchase Price\u201d), which shall be paid at the Closing (defined below) by cash, '
        f'certified check or wire transfer.'
    )

    # C. Deposit
    init_dep = fmt_dollar(form.initial_deposit) if form.initial_deposit and form.initial_deposit > 0 else "[Ten Thousand and 00/100 Dollars ($10,000.00)]"
    add_dep = fmt_dollar(form.additional_deposit) if form.additional_deposit and form.additional_deposit > 0 else "[Ten Thousand and 00/100 Dollars ($10,000.00)]"
    monthly_rel = fmt_dollar(form.monthly_release_amount) if form.monthly_release_amount and form.monthly_release_amount > 0 else "[Five Thousand and 00/100 Dollars ($5,000.00)]"

    if form.deposit_structure == DepositStructure.GOVERNMENTAL_APPROVALS_GOING_HARD:
        deposit_text = (
            f'Within five (5) business days following mutual execution of the Purchase Agreement '
            f'(as defined below), {init_dep} (\u201cInitial Deposit\u201d) shall be delivered to First American Title Insurance, '
            f'National Commercial Services (\u201cTitle Company\u201d). If, prior to the expiration of the Due Diligence Period '
            f'(as defined below), Purchaser determines not to pursue the transaction, Purchaser may terminate the Purchase Agreement, '
            f'and the Initial Deposit shall be fully and promptly refunded to Purchaser. Otherwise, Purchaser shall deposit an additional '
            f'sum into escrow with the Title Company in the amount of {add_dep} (\u201cAdditional Deposit\u201d, which together with '
            f'the Initial Deposit, is referred to herein as the (\u201cEarnest Money\u201d). The Earnest Money shall be non-refundable '
            f'to the Purchaser subject to (i) Purchaser\u2019s receipt of Governmental Approvals, during the Governmental Approvals Period '
            f'(as defined below), (ii) a default by Seller under the Purchase Agreement, or (iii) a casualty or a condemnation, each as '
            f'shall be further defined in the Purchase Agreement. If the Purchaser has not obtained the Governmental Approvals during the '
            f'Governmental Approvals Period, Purchaser may terminate the Purchase Agreement, and the Earnest Money shall be fully and promptly '
            f'refunded to Purchaser. Otherwise, the Earnest Money shall become non-refundable to the Purchaser upon expiration of the '
            f'Governmental Approvals Period (except as expressly set forth in the Purchase Agreement). The Earnest Money shall be applied '
            f'towards the Purchase Price at Closing.'
        )
    elif form.deposit_structure == DepositStructure.DUE_DILIGENCE_GOING_HARD:
        deposit_text = (
            f'Within five (5) business days following mutual execution of the Purchase Agreement '
            f'(as defined below), {init_dep} (\u201cInitial Deposit\u201d) shall be delivered to First American Title Insurance, '
            f'National Commercial Services (\u201cTitle Company\u201d). If, prior to the expiration of the Due Diligence Period '
            f'(as defined below), Purchaser determines not to pursue the transaction, Purchaser may terminate the Purchase Agreement, '
            f'and the Initial Deposit shall be fully and promptly refunded to Purchaser. Otherwise, upon waiver of the Due Diligence Period, '
            f'the Initial Deposit shall become non-refundable to the Purchaser, and Purchaser shall deposit an additional sum into escrow '
            f'with the Title Company in the amount of {add_dep} (\u201cAdditional Deposit\u201d, which together with the Initial Deposit, '
            f'is referred to herein as the (\u201cEarnest Money\u201d). The Additional Deposit shall be non-refundable to the Purchaser '
            f'subject to (i) Purchaser\u2019s receipt of the Governmental Approvals during the Governmental Approvals Period (as defined below), '
            f'(ii) a default by Seller under the Purchase Agreement, or (iii) a casualty or a condemnation, each as shall be further defined '
            f'in the Purchase Agreement. If Purchaser has not obtained the Governmental Approvals during the Governmental Approvals Period, then '
            f'Purchaser may terminate the Purchase Agreement, and the Additional Deposit shall be fully and promptly refunded to Purchaser. '
            f'Otherwise, the Additional Deposit shall become non-refundable to the Purchaser upon expiration of the Governmental Approvals Period '
            f'(except as expressly set forth in the Purchase Agreement). The Earnest Money shall be applied towards the Purchase Price at Closing.'
        )
    else:  # Monthly Going Hard
        deposit_text = (
            f'Within five (5) business days following mutual execution of the Purchase Agreement '
            f'(as defined below), {init_dep} (the \u201cInitial Deposit\u201d) shall be delivered to First American Title Insurance, '
            f'National Commercial Services (the \u201cTitle Company\u201d). If, prior to the expiration of the Due Diligence Period '
            f'(as defined below), Purchaser determines not to pursue the transaction, Purchaser may terminate the Purchase Agreement and '
            f'the Initial Deposit shall be fully and promptly refunded to Purchaser. Otherwise, Purchaser shall deposit an additional sum '
            f'into escrow with the Title Company in the amount of {add_dep} (the \u201cAdditional Deposit\u201d, which together with '
            f'the Initial Deposit, is referred to herein as the \u201cEarnest Money\u201d) and shall be non-refundable to the Purchaser, '
            f'subject to (i) Purchaser\u2019s receipt of the Governmental Approvals during the Governmental Approvals Period (as defined below), '
            f'(ii) a default by Seller under the Purchase Agreement, or (iii) a casualty or a condemnation, each as shall be further defined '
            f'in the Purchase Agreement. On the 1st of each month following waiver of the Due Diligence Period, {monthly_rel} of the Earnest Money '
            f'(collectively, the \u201cMonthly Releases\u201d), shall become non-refundable to the Purchaser, subject to a default by Seller '
            f'under the Purchase Agreement, and shall be immediately released to the Seller by Title Company. If Purchaser has not obtained the '
            f'Governmental Approvals during the Governmental Approvals Period, Purchaser may terminate the Purchase Agreement and the Earnest Money, '
            f'less the Monthly Releases paid to date, shall be fully and promptly refunded to Purchaser. Otherwise, the Earnest Money shall become '
            f'non-refundable to the Purchaser upon expiration of the Governmental Approvals Period (except as expressly set forth in the Purchase '
            f'Agreement). The Earnest Money shall be applied towards the Purchase Price at Closing.'
        )

    if form.deposit_structure == DepositStructure.GOVERNMENTAL_APPROVALS_GOING_HARD:
        lines.append(f"C. Deposit. {deposit_text}")
    else:
        lines.append(f"C. {deposit_text}")

    # Legal Reimbursement
    if form.include_legal_reimbursement:
        lr = fmt_dollar(form.legal_reimbursement_amount) if form.legal_reimbursement_amount and form.legal_reimbursement_amount > 0 else "[Five Thousand and 00/100 Dollars ($5,000.00)]"
        lines.append(
            f'Legal Reimbursement Fee. Upon mutual execution of the Purchase Agreement, '
            f'{lr} shall be immediately released to the Seller by the Title Company (\u201cLegal Reimbursement Fee\u201d) '
            f'and shall be non-refundable to the Purchaser, subject to a default by Seller under the Purchase Agreement, '
            f'a casualty or a condemnation.'
        )

    # D. Exclusivity
    lines.append(
        'D. Exclusivity; Seller\u2019s Covenants. '
        'Upon mutual execution of this proposal, Purchaser shall have thirty (30) days (\u201cExclusivity Period\u201d) to negotiate '
        'on an exclusive basis a definitive purchase agreement for the Property (\u201cPurchase Agreement\u201d), which Purchase Agreement '
        'shall be prepared by Purchaser and provided to Seller promptly after execution of this proposal. During the Exclusivity Period and '
        'while the Purchase Agreement is in effect, subject to Paragraph I, Seller shall (a) not negotiate with any other party or sell or '
        'lease, offer to sell or lease, accept an offer to purchase or lease or solicit or respond to solicitations for the sale or lease of '
        'any portion of or interest in the Property, (b) not execute any contracts, leases, easements or other documents or grant any rights to '
        'or affecting the Property or take any other material actions affecting the Property without Purchaser\u2019s prior written consent, and '
        '(c) continue to manage and maintain the Property as it is currently being managed and maintained.'
    )

    # E. Due Diligence
    dd_val = fmt_period_val(form.due_diligence_days) if form.due_diligence_days else "[one hundred twenty (120)]"
    ga_val = fmt_period_val(form.governmental_approvals_days) if form.governmental_approvals_days else "[one hundred fifty (150)]"

    if form.due_diligence_type == DueDiligenceType.STANDARD:
        lines.append(
            f'E. Due Diligence and Governmental Approvals. '
            f'Purchaser shall have a period of {dd_val} days after mutual execution of the Purchase Agreement '
            f'(\u201cDue Diligence Period\u201d) to inspect and investigate the Property to the extent deemed necessary or desirable '
            f'by Purchaser in its sole and absolute discretion. Upon expiration of the Due Diligence Period, Purchaser shall have a period of '
            f'{ga_val} days (\u201cGovernmental Approvals Period\u201d) to procure all zoning approvals, permits, consents, authorizations, '
            f'variances, waivers, licenses, certificates and other approvals from any governmental or quasi-governmental authority with respect '
            f'to the Property necessary or desirable, in Purchaser\u2019s sole and absolute discretion (collectively, \u201cGovernmental Approvals\u201d).'
        )
    else:
        asm_val = fmt_period_val(form.assemblage_days) if form.assemblage_days else "[ninety (90)]"
        lines.append(
            f'E. Assemblage; Due Diligence; Governmental Approvals. '
            f'Purchaser shall have a period of {asm_val} days after mutual execution of the Purchase Agreement '
            f'(\u201cAssemblage Period\u201d) to execute purchase agreements with all necessary adjacent parcels, in Purchaser\u2019s '
            f'sole and absolute discretion. Upon expiration of the Assemblage Period, Purchaser shall have a period of {dd_val} days '
            f'(\u201cDue Diligence Period\u201d) to inspect and investigate the Property to the extent deemed necessary or desirable by '
            f'Purchaser in its sole and absolute discretion. Upon expiration of the Due Diligence Period, Purchaser shall have a period of '
            f'{ga_val} days (\u201cGovernmental Approvals Period\u201d) to procure all zoning approvals, permits, consents, authorizations, '
            f'variances, waivers, licenses, certificates and other approvals from any governmental or quasi-governmental authority with respect '
            f'to the Property necessary or desirable, in Purchaser\u2019s sole and absolute discretion (collectively, \u201cGovernmental Approvals\u201d).'
        )

    # F. Closing
    cl_val = fmt_period_val(form.closing_days) if form.closing_days else "[thirty (30)]"
    closing_text = f'Within {cl_val} days after the expiration of the Governmental Approvals Period (\u201cClosing\u201d).'

    if form.include_closing_extension:
        ext_m = fmt_period_val(form.closing_extension_months) if form.closing_extension_months else "[six (6)]"
        ext_d = fmt_dollar(form.monthly_closing_extension_deposit) if form.monthly_closing_extension_deposit else "[Twenty-Five Thousand and 00/100 Dollars ($25,000.00)]"
        closing_text += (
            f' Notwithstanding the foregoing, Purchaser shall have the right to extend the Closing on a month-to-month basis '
            f'for up to a total of {ext_m} months (each a \u201cClosing Extension\u201d) by delivering to the Title Company '
            f'a deposit in the amount of {ext_d} for each month of extension (\u201cMonthly Closing Extension Deposit\u201d). '
            f'The Monthly Closing Extension Deposits shall be non-refundable to the Purchaser when made, subject to a default by '
            f'Seller under the Purchase Agreement, a casualty or a condemnation, but shall be applicable to the Purchase Price.'
        )
    lines.append(f"F. Closing. {closing_text}")

    # G. Commissions
    if form.commission_type == CommissionType.SELLER_PAYS_LISTING_AGENT:
        comm = ('Seller to pay the commission set forth in the listing agreement at Closing, and Purchaser and Seller '
                'agree no other brokerage commissions are due as a result of this transaction.')
    elif form.commission_type == CommissionType.SUBTEXT_PAYS:
        broker = form.broker_name or "[_____________]"
        comm = (f'Purchaser to pay a commission at Closing to {broker} pursuant to a separate agreement, '
                f'and Purchaser and Seller agree no other brokerage commissions are due as a result of this transaction.')
    else:
        comm = 'Purchaser and Seller agree that no brokerage commission is due as a result of this transaction.'
    lines.append(f"G. Commissions. {comm}")

    # H. Option to Extend
    if form.include_option_to_extend:
        ext_dep = fmt_dollar(form.extension_deposit_amount) if form.extension_deposit_amount and form.extension_deposit_amount > 0 else "[Five Thousand and 00/100 Dollars ($5,000.00)]"
        lines.append(
            f'H. Option to Extend. '
            f'Purchaser shall have a total of two (2) sixty (60) day extension options (each an \u201cOption to Extend\u201d). '
            f'Each Option to Extend may be applied to the Due Diligence Period or the Governmental Approvals Period by delivering '
            f'written notice to the Seller prior to the expiration of such term (\u201cExtension Notice\u201d) and delivering to the '
            f'Title Company an amount equal to {ext_dep} (\u201cExtension Deposit\u201d) within five (5) business days of the '
            f'Extension Notice. The Extension Deposits shall be non-refundable to the Purchaser when made, subject to a default by '
            f'Seller under the Purchase Agreement but shall be applicable to the Purchase Price.'
        )

    # I. Leases
    lease_parts = []
    if form.include_existing_leases:
        le = form.lease_end_date or "[May 31, 2026]"
        lease_parts.append(
            f'Purchaser and Seller agree there are existing leases on the Property and that all existing leases end on or before {le}.'
        )
    if form.include_delivered_vacant:
        lease_parts.append(
            'Seller agrees to terminate, effective as of Closing, all leases such that the Property shall be delivered vacant at Closing, '
            'and Seller shall be responsible for all monetary penalties/fees and or settlements related to the termination of leases. '
            'If any tenant asserts a claims or files a lawsuit against the Property, the Seller, or the Purchaser in connection with or '
            'related to such termination, the Seller shall be solely responsible for all costs and fees related to defending such claims '
            'or lawsuits and shall indemnify, defend and hold the Purchaser harmless from any loss, cost, expenses and liability related thereto.'
        )
    if form.include_lease_termination:
        lt = fmt_period_val(form.lease_termination_days) if form.lease_termination_days else "[sixty (60)]"
        lease_parts.append(
            f'All new leases and renewals of existing leases entered into after the date hereof, shall include a {lt} day '
            f'termination provision that shall be further defined in the Purchase Agreement.'
        )
    if form.include_right_to_negotiate_with_tenants:
        lease_parts.append(
            'Upon mutual execution of this proposal, Purchaser shall have the right to negotiate directly with the existing tenants '
            'regarding a potential lease amendment, provided that Seller shall have the right to facilitate such introductions.'
        )
    if lease_parts:
        lines.append(f"I. Leases. {' '.join(lease_parts)}")

    # Seller Rollover
    if form.include_seller_rollover:
        lines.append(
            'Seller Rollover Option for Project Equity. '
            'In concert with the execution of the Purchase Agreement, Seller shall have the right, but not an obligation, to invest '
            'up to one hundred (100%) percent of his/her/its/their sale price as equity in the Purchaser\u2019s intended project '
            '(\u201cProject\u201d), with such investment being through a limited liability company or other entity type selected by '
            'the Purchaser in good faith, that will be an indirect owner of the Property, whereby Seller shall be a passive investor '
            '(no day to day or major decision rights) in the Project, but with Seller being entitled to substantially the same '
            '\u201climited partner\u201d returns on equity as the to be selected capital partner for the Project will receive '
            '(\u201cCapital Partner\u201d). For the avoidance of doubt, the Seller shall not participate in any fees payable to '
            'Purchaser or its affiliates that are approved by the Capital Partner or Project\u2019s lender.'
        )

    # J. Confidentiality
    lines.append(
        'J. Confidentiality. '
        'During the Exclusivity Period and, while the Purchase Agreement is in effect, Purchaser and Seller shall keep all negotiations '
        'and communications between the parties regarding the potential purchase of the Property confidential and shall not disclose '
        'any matter related to such negotiations and communications to any third party. The parties hereto may disclose this proposal '
        'and the term hereof to their respective brokers, legal counsel, tax advisors, officers, directors, employees, partners, '
        'investors or lenders, each of whom shall be directed to uphold similar standards of confidentiality.'
    )

    # K. Governing Law
    lines.append(
        'K. Governing Law. '
        'This proposal shall be governed by the laws of the State of Missouri, without giving effect to conflict of laws principles.'
    )

    # L. Miscellaneous
    lines.append(
        'L. Miscellaneous. '
        'This proposal may be signed in counterparts with the same effect as if executed on a single document. This proposal constitutes '
        'the entire agreement between the parties concerning the subject matter hereof and supersedes all prior representations, '
        'understandings or agreements, whether oral or written. This proposal may be modified only by a written instrument executed '
        'by both parties. Apart from the \u201cExclusivity; Seller\u2019s Covenants and Confidentiality\u201d paragraphs above, '
        'this proposal is not intended to be binding and shall not create any legal or equitable obligations unless and until a '
        'definitive Purchase Agreement is executed.'
    )

    # Closing paragraph
    lines.append(
        'If the foregoing is acceptable, please indicate by executing a copy of this proposal and returning '
        'it to the undersigned. We look forward to working with you on this transaction.'
    )

    # Signature
    lines.append("Sincerely,")
    lines.append("Subtext Acquisitions, LLC")
    lines.append("Richard Birner, Vice President of Land Acquisitions")
    lines.append("Agreed and Accepted by Seller this _____ day of ___________, 2026")

    if form.signature_block_type == SignatureBlockType.INDIVIDUAL:
        if form.seller_name_signature:
            lines.append(form.seller_name_signature)
    else:
        for ent in form.signature_entities:
            if ent.company_name:
                lines.append(ent.company_name)
            lines.append("By:________________________")
            lines.append("Name:________________________")
            lines.append("Title:________________________")

    # Exhibit A
    lines.append("EXHIBIT A")
    lines.append("DEPICTION OF PROPERTY")
    lines.append("PARCEL ID NUMBER(S)")
    for pid in form.parcel_ids:
        if pid.strip():
            lines.append(pid.strip())

    return lines


# =========================================================================
# Main comparison
# =========================================================================
def run_comparison(form: LoiFormData, scenario_name: str):
    print(f"\n{'='*70}")
    print(f"  SCENARIO: {scenario_name}")
    print(f"{'='*70}")

    gen = DocumentGenerator()
    buf = gen.generate(TEMPLATE_PATH, form)
    doc = Document(buf)
    body = doc.element.body

    doc_paragraphs = get_visible_paragraphs(body)
    doc_headers = get_header_visible_text(doc)
    ui_lines = build_ui_preview_text(form)

    # Normalize all for comparison
    doc_normalized = [normalize(p) for p in doc_paragraphs if normalize(p)]
    ui_normalized = [normalize(l) for l in ui_lines if normalize(l)]

    # Strip auto-numbered letter prefixes from UI text for comparison.
    # The Word template uses StandardL1 style with upperLetter numbering,
    # which auto-generates "A.", "B.", etc. These appear in Word but
    # aren't in w:t text nodes.
    ui_stripped = [strip_letter_prefix(t) for t in ui_normalized]

    discrepancies = []

    # Check each UI line exists in the document
    for i, ui_text in enumerate(ui_stripped):
        found = False
        for doc_text in doc_normalized:
            # Check if the UI text is contained in (or matches) a doc paragraph
            if ui_text in doc_text or doc_text in ui_text:
                found = True
                # Check for exact match
                if ui_text != doc_text:
                    # Find the difference
                    if len(ui_text) > 50 and len(doc_text) > 50:
                        # Long text - find first difference
                        min_len = min(len(ui_text), len(doc_text))
                        diff_pos = next((j for j in range(min_len) if ui_text[j] != doc_text[j]), min_len)
                        context_start = max(0, diff_pos - 30)
                        context_end = min(max(len(ui_text), len(doc_text)), diff_pos + 50)
                        discrepancies.append({
                            "type": "TEXT_MISMATCH",
                            "ui_section": ui_text[:80] + "...",
                            "diff_pos": diff_pos,
                            "ui_context": ui_text[context_start:context_end],
                            "doc_context": doc_text[context_start:min(context_end, len(doc_text))],
                        })
                break

        if not found:
            # Check headers too
            for h_text in doc_headers:
                h_norm = normalize(h_text)
                if ui_text in h_norm or h_norm in ui_text:
                    found = True
                    break

        if not found:
            discrepancies.append({
                "type": "UI_ONLY",
                "text": ui_text[:120],
            })

    # Check each doc paragraph exists in UI
    for doc_text in doc_normalized:
        found = False
        for ui_text in ui_stripped:
            if doc_text in ui_text or ui_text in doc_text:
                found = True
                break
        # Also check headers
        if not found:
            for h_text in doc_headers:
                if doc_text in normalize(h_text) or normalize(h_text) in doc_text:
                    found = True
                    break
        if not found:
            # Skip signature underlines and blank-ish content
            if doc_text.startswith("____") or doc_text in ("By:", "Name:", "Title:"):
                continue
            discrepancies.append({
                "type": "DOC_ONLY",
                "text": doc_text[:120],
            })

    if discrepancies:
        print(f"\n  Found {len(discrepancies)} discrepancies:\n")
        for d in discrepancies:
            if d["type"] == "UI_ONLY":
                print(f"  [UI ONLY] Text in preview but not in document:")
                print(f"    \"{d['text']}\"")
            elif d["type"] == "DOC_ONLY":
                print(f"  [DOC ONLY] Text in document but not in preview:")
                print(f"    \"{d['text']}\"")
            elif d["type"] == "TEXT_MISMATCH":
                print(f"  [MISMATCH] Text differs at position {d['diff_pos']}:")
                print(f"    UI:  \"{d['ui_context']}\"")
                print(f"    DOC: \"{d['doc_context']}\"")
            print()
    else:
        print("\n  No discrepancies found!")

    return len(discrepancies)


# =========================================================================
# Run all scenarios
# =========================================================================
if __name__ == "__main__":
    if not os.path.exists(TEMPLATE_PATH):
        print(f"ERROR: Template not found at {TEMPLATE_PATH}")
        sys.exit(1)

    total_disc = 0

    # Scenario 1: Default (Gov Approvals, Standard DD, all defaults)
    form1 = LoiFormData(
        date="March 1, 2026",
        property_address="123 Main St, Springfield, IL 62701",
        seller_address_line1="Acme Properties LLC",
        seller_address_line2="100 Commerce Dr",
        seller_address_line3="Springfield, IL 62701",
        attention_name="John Doe",
        salutation="Mr. Doe",
        seller_name="Acme Properties LLC",
        purchase_price=500000,
        initial_deposit=10000,
        additional_deposit=10000,
        deposit_structure=DepositStructure.GOVERNMENTAL_APPROVALS_GOING_HARD,
        due_diligence_type=DueDiligenceType.STANDARD,
        due_diligence_days=120,
        governmental_approvals_days=150,
        closing_days=30,
        include_closing_extension=False,
        commission_type=CommissionType.SELLER_PAYS_LISTING_AGENT,
        include_option_to_extend=True,
        extension_deposit_amount=5000,
        include_existing_leases=True,
        lease_end_date="May 31, 2026",
        include_delivered_vacant=False,
        include_lease_termination=False,
        include_right_to_negotiate_with_tenants=False,
        include_seller_rollover=False,
        signature_block_type=SignatureBlockType.INDIVIDUAL,
        seller_name_signature="John Doe",
        parcel_ids=["12-345-678"],
        prepared_by_first_name="Jake",
        prepared_by_last_name="Miller",
    )
    total_disc += run_comparison(form1, "Default: Gov Approvals, Standard DD, Individual Sig")

    # Scenario 2: DD Going Hard, Assemblage, Closing Extension, Subtext Pays, Company Entity
    form2 = LoiFormData(
        date="April 15, 2026",
        property_address="456 Oak Ave, St. Louis, MO 63101",
        seller_address_line1="Beta Holdings Inc",
        seller_address_line2="200 Business Blvd",
        seller_address_line3="St. Louis, MO 63101",
        attention_name="Jane Smith",
        salutation="Ms. Smith",
        seller_name="Beta Holdings Inc",
        purchase_price=1250000,
        initial_deposit=15000,
        additional_deposit=25000,
        deposit_structure=DepositStructure.DUE_DILIGENCE_GOING_HARD,
        due_diligence_type=DueDiligenceType.WITH_ASSEMBLAGE,
        due_diligence_days=120,
        governmental_approvals_days=150,
        assemblage_days=90,
        closing_days=45,
        include_closing_extension=True,
        closing_extension_months=6,
        monthly_closing_extension_deposit=25000,
        commission_type=CommissionType.SUBTEXT_PAYS,
        broker_name="Elite Realty",
        include_option_to_extend=True,
        extension_deposit_amount=8000,
        include_existing_leases=True,
        lease_end_date="December 31, 2026",
        include_delivered_vacant=True,
        include_lease_termination=True,
        lease_termination_days=60,
        include_right_to_negotiate_with_tenants=True,
        include_seller_rollover=True,
        signature_block_type=SignatureBlockType.COMPANY_ENTITY,
        signature_entities=[
            SignatureEntity(company_name="Beta Holdings Inc"),
            SignatureEntity(company_name="Gamma Ventures LLC"),
        ],
        parcel_ids=["11-222-333", "44-555-666"],
        prepared_by_first_name="Sarah",
        prepared_by_last_name="Johnson",
    )
    total_disc += run_comparison(form2, "DD Going Hard, Assemblage, Extension, Subtext Pays, Company Entity")

    # Scenario 3: Monthly Going Hard, No Brokers, Legal Reimbursement
    form3 = LoiFormData(
        date="May 20, 2026",
        property_address="789 Elm St, Kansas City, MO 64101",
        seller_address_line1="Charlie Real Estate Trust",
        seller_address_line2="",
        seller_address_line3="Kansas City, MO 64101",
        attention_name="Bob Williams",
        salutation="Mr. Williams",
        seller_name="Charlie Real Estate Trust",
        purchase_price=750000,
        initial_deposit=10000,
        monthly_release_amount=7500,
        deposit_structure=DepositStructure.MONTHLY_GOING_HARD,
        include_legal_reimbursement=True,
        legal_reimbursement_amount=5000,
        due_diligence_type=DueDiligenceType.STANDARD,
        due_diligence_days=90,
        governmental_approvals_days=120,
        closing_days=30,
        include_closing_extension=False,
        commission_type=CommissionType.NO_BROKERS,
        include_option_to_extend=False,
        include_existing_leases=False,
        include_delivered_vacant=True,
        include_lease_termination=False,
        include_right_to_negotiate_with_tenants=False,
        include_seller_rollover=False,
        signature_block_type=SignatureBlockType.INDIVIDUAL,
        seller_name_signature="Bob Williams",
        parcel_ids=["99-888-777"],
        prepared_by_first_name="Mike",
        prepared_by_last_name="Davis",
    )
    total_disc += run_comparison(form3, "Monthly Going Hard, No Brokers, Legal Reimbursement, Empty Addr Line 2")

    print(f"\n{'='*70}")
    print(f"  TOTAL DISCREPANCIES: {total_disc}")
    print(f"{'='*70}")

    sys.exit(1 if total_disc > 0 else 0)
